# Generated by Django 4.2.13 on 2024-06-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
