# Generated by Django 4.2.13 on 2024-06-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0005_alter_componentesequipo_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='equipo',
            field=models.ManyToManyField(to='AppInventario.equipo'),
        ),
    ]
