# Generated by Django 4.2.13 on 2024-06-07 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0007_remove_producto_equipo_tipoproducto_tipo_equipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='equipo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='AppInventario.equipo'),
        ),
        migrations.DeleteModel(
            name='ComponentesEquipo',
        ),
    ]
