# Generated by Django 4.2.13 on 2024-06-07 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0009_alter_producto_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='equipo',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='AppInventario.equipo'),
        ),
    ]
