# Generated by Django 4.2.13 on 2024-06-07 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0010_alter_producto_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=150)),
                ('numero_serie', models.CharField(blank=True, max_length=200)),
                ('equipo', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='AppInventario.equipo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppInventario.marca')),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppInventario.tipoproducto')),
            ],
        ),
        migrations.AlterField(
            model_name='ordenegreso',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppInventario.producto2'),
        ),
        migrations.AlterField(
            model_name='ordeningreso',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppInventario.producto2'),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
