# Generated by Django 4.2.13 on 2024-06-07 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0011_producto2_alter_ordenegreso_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto2',
            name='equipo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='AppInventario.equipo'),
        ),
    ]
