# Generated by Django 4.2.13 on 2024-06-07 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0013_alter_producto2_equipo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto2',
            new_name='Producto',
        ),
    ]
