# Generated by Django 4.2.13 on 2024-06-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0016_alter_marca_nombre_alter_producto_numero_serie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenegreso',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ordeningreso',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rut',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
