# Generated by Django 4.2.13 on 2024-06-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0017_alter_ordenegreso_fecha_alter_ordeningreso_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoproducto',
            name='tipo_equipo',
        ),
        migrations.AddField(
            model_name='tipoequipo',
            name='tipo_producto',
            field=models.ManyToManyField(to='AppInventario.tipoproducto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
