# Generated by Django 4.2.13 on 2024-06-12 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0018_remove_tipoproducto_tipo_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='equipo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='AppInventario.equipo'),
        ),
    ]
