# Generated by Django 4.2.13 on 2024-06-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0020_alter_producto_equipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='equipo',
        ),
        migrations.AddField(
            model_name='equipo',
            name='productos',
            field=models.ManyToManyField(blank=True, null=True, to='AppInventario.producto'),
        ),
    ]
