# Generated by Django 4.2.13 on 2024-06-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0021_remove_producto_equipo_equipo_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='productos',
            field=models.ManyToManyField(blank=True, to='AppInventario.producto'),
        ),
    ]
