# Generated by Django 4.2.13 on 2024-07-04 10:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0022_alter_equipo_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordeningreso',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='ordeningreso',
            name='producto',
        ),
        migrations.CreateModel(
            name='DetalleIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.StepValueValidator(1)])),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppInventario.ordeningreso')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppInventario.producto')),
            ],
        ),
    ]
