# Generated by Django 4.2.13 on 2024-06-27 22:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0022_alter_equipo_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='comuna',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email_contacto',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='region',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono_contacto',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
    ]
