# Generated by Django 4.2.13 on 2024-07-04 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0023_remove_ordeningreso_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenegreso',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='ordenegreso',
            name='producto',
        ),
        migrations.CreateModel(
            name='DetalleEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppInventario.ordenegreso')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppInventario.producto')),
            ],
        ),
    ]
