# Generated by Django 4.2.13 on 2024-07-04 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0024_remove_ordenegreso_cantidad_and_more'),
        ('AppInventario', '0025_poblar_regiones_y_comunas'),
    ]

    operations = [
    ]
